### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by cris0828** [LittleTurtle2333/SimplicityTools#25]
**描述一下BUG情况
状态栏网速无法秒刷新，大约5s刷新一次

**如何复现**
复现的步骤
1. 去  '...'
2. 点击  '....'
3. 滚动到  '....'
4. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问题。

**手机信息：**
 - 设备型号：小米10
 - MIUI版本：22.3.3
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by LittleTurtle2333** [comment]
不存在此问题
