### ISSUE TITLE
[BUG]妙享中心版控制中心无法显示天气，通知中心正常显示

### ISSUE THREAD

**Issue by cris0828** [LittleTurtle2333/SimplicityTools#28]
**描述一下BUG情况**
清晰明了的描述BUG的情况

**如何复现**
复现的步骤
1. 去  '...'
2. 点击  '....'
3. 滚动到  '....'
4. 问题出现

**截图**
如果可以，请添加截图以帮助解释您的问题。

**手机信息：**
 - 设备型号：小米10
 - MIUI版本：22.3.3
 - Android版本：12

**附加信息**
在此处添加有关此问题的任何其他内容。

**Comment by LittleTurtle2333** [comment]
不然为什么叫下拉通知天气

**Comment by cris0828** [comment]
> 不然为什么叫下拉通知天气

好吧，懂了
