### ISSUE TITLE
天气功能在经典控制中心无效[BUG]

### ISSUE THREAD

**Issue by rxzcums** [LittleTurtle2333/SimplicityTools#35]
**描述一下BUG情况**
RT
**如何复现**
复现的步

**截图**
如果可以，请添加截图以帮助解释您的问题。

**手机信息：**
 - 设备型号：k40
 - MIUI版本：13
 - Android版本：12

**附加信息**
无

**Comment by LittleTurtle2333** [comment]
![Screenshot_2022-03-10-01-23-36-537_org.telegram.messenger.jpg](https://user-images.githubusercontent.com/32336368/157496765-87fcf106-7380-434b-aa29-086df584dcfd.jpg)

已适配，明天推送
