### ISSUE TITLE
能隐藏竖线就完美了

### ISSUE THREAD

**Issue by iocd** [LittleTurtle2333/SimplicityTools#36]
请清晰明了地讲述您的建议
小米12，安卓12，miui13

1,状态栏有竖线，感觉不好看。
2,网速小于10k自动隐藏可能更简洁些
![Screenshot_2022-03-07-15-57-54-437_com lt2333 simplicitytools](https://user-images.githubusercontent.com/44340858/156991386-dbd36970-70fe-48af-9a21-6843aa3b4362.jpg)

其他：在【小米净化】里看到有网速低于10k自动隐藏的，但是在我的小米12上不生效。下边是相关资料：
https://github.com/coderstory/Mi-Purify
![Screenshot_2022-03-07-16-04-39-462_com coderstory purify](https://user-images.githubusercontent.com/44340858/156992252-9aa63218-479c-4e99-abae-2d78f3577a7c.jpg)

**Comment by LittleTurtle2333** [comment]
已适配去除分隔符
