### ISSUE TITLE
[Feature]自定义应用通知的排列优先级

### ISSUE THREAD

**Issue by cccccpppppp** [LittleTurtle2333/SimplicityTools#44]
比如我的耳机功能栏老是排在最下面，希望可以根据自定义应用的优先级来排列通知![Screenshot_2022-03-11-02-40-11-210_com.miui.home.jpg](https://user-images.githubusercontent.com/24277775/157732417-60986972-2741-4cf0-ad1d-5c884e652786.jpg)

**Comment by LittleTurtle2333** [comment]
已支持
